Adds two new entities (Ablufttaupunkt & Differenzdruck)
kr0ner/OneESP32ToRuleThemAll pull request #30
Opened 2024-09-22 18:19 UTC by Hotdogxxxx

2024-09-23 20:23 UTC, kr0ner requested changes

2024-09-23 20:28 UTC, kr0ner commented
Can you please also squash your changes? We don't need 4 commits for a small change ;)

2024-09-24 06:46 UTC, Hotdogxxxx commented
The number of commits is because I have been making the changes directly in GITHUB. Every time a file changes, A separate commit is triggered.

2024-09-24 06:46 UTC, closed without merging

2024-09-24 07:11 UTC, kr0ner commented
Ok, then I will just squash merge them next time